GET http://localhost:8080/api/v1/product/3

### add image to product
POST /api/v1/admin/product/2/image
Host: localhost:8080
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="fray_stay_right_1.png"
Content-Type: image/png

< ./fray_stay_right_1.png

--WebAppBoundary--


###
POST http://localhost:8080/shop/api/v1/admin/product
Content-Type: application/json

{
  "id": 1,
  "title": "продукттт",
  "cost": "10.2",
  "categoryId": 10
}

###
PUT http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "id": 1000,
  "title": "пр1",
  "cost": "10.2",
  "categoryId": 10
}


###
POST http://localhost:8080/shop/api/v1/product/list
Content-Type: application/json

{
  "currPage": 1
}


###
###
POST http://localhost:8080/api/v1/product/costs
Content-Type: application/json

[4, 8, 10]



###
GET http://localhost:8080/api/v1/category/2


###
POST http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "title": "Десятая",
  "parentCategoryId": 20
}

###
PUT http://localhost:8080/api/v1/category
Content-Type: application/json

{
  "id": 17,
  "title": "Восьмаяяяяя",
  "parentCategoryId": 17
}


###
DELETE http://localhost:8080/api/v1/category/9


###
GET http://localhost:8080/shop/api/v1/category


###
POST http://localhost:8080/api/v1/user/auth
Content-Type: application/x-www-form-urlencoded

login=user&password=1


###
#SOAP

GET http://localhost:8080/shop/ws/categories.wsdl

###

GET http://localhost:8080/ws/products.wsdl

###

POST http://localhost:8080/ws
Content-Type: text/xml; charset=utf-8

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://www.darvell.ru/spring/ws/categories">
    <x:Header/>
    <x:Body>
        <gre:getAllCategoriesFlatRequest/>
    </x:Body>
</x:Envelope>

###
POST http://localhost:8080/ws
Content-Type: text/xml; charset=utf-8

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:gre="http://www.darvell.ru/spring/ws/products">
    <x:Header/>
    <x:Body>
        <gre:getAllProductsRequest/>
    </x:Body>
</x:Envelope>


###
OPTIONS http://localhost:8080/shop/api/v1/category



###
POST http://localhost:8080/shop/api/v1/grade/review
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzIiwiZXhwIjoxNjM0OTI0MzA2fQ.SAuyktIMyy2I3h3kqWypzqdYkw0F1YgjLoSeh0VS6Nbukbiy4rSZ54Jch9A_65yYjlnayLeHwnIx4i_W95DqKQ

{
  "productId": "34",
  "pluses": "Много плюсов",
  "minuses": "Много минусов"

}



####
GET http://localhost:8080/shop/api/v1/grade/review/by_product/34



###
POST http://localhost:8080/shop/api/v1/order
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzIiwiZXhwIjoxNjM0OTI0MzA2fQ.SAuyktIMyy2I3h3kqWypzqdYkw0F1YgjLoSeh0VS6Nbukbiy4rSZ54Jch9A_65yYjlnayLeHwnIx4i_W95DqKQ


{
  "deliveryAddress": "Адрес",
  "comment" : "Комментарий к заказу",
  "shopOrderItems" : [
    {
      "productId": 2,
      "count": 3
    },
    {
      "productId": 2,
      "count": 4
    }
  ]
}

###
POST http://localhost:8080/shop/api/v1/order/by_current_user
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzIiwiZXhwIjoxNjM0OTI0MzA2fQ.SAuyktIMyy2I3h3kqWypzqdYkw0F1YgjLoSeh0VS6Nbukbiy4rSZ54Jch9A_65yYjlnayLeHwnIx4i_W95DqKQ

{
  "currPage": 0,
  "pageSize": 3,
  "sortField": "id"
}


