spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple_app
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  application:
    name: shop
server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    appname: shop
#    hostname: http://localhost:8080/
#ribbon:
#  eureka:
#    enabled: true
