server:
  port: 8090
eureka:
  dashboard:
    path: /eureka-dash
  client:
    registerWithEureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8090/eureka
  server:
    enableSelfPreservation: true
ribbon:
  eureka:
    enabled: true
spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
zuul:
  routes:
    config:
      path: /config/**
      serviceId: config
    shop:
      path: /shop/**
      serviceId: shop
